name: pocket
version: 20200213
email: ourfor@qq.com
author: ourfor
host: https://pocket.ourfor.top

theme:
  - star
  - simple
  - light
  - night

api:
  host: http://localhost:8443
  # host: http://39.104.110.210:8443
  headers: 
    "Content-Type": application/json


lesson:
  weekday: 
    - 周日
    - 周一
    - 周二 
    - 周三 
    - 周四 
    - 周五 
    - 周六
  period:
    - 上午 第一节课
    - 上午 第二节课
    - 上午 第三节课
    - 上午 第四节课
    - 下午 第一节课
    - 下午 第二节课
    - 下午 第三节课 
    - 下午 第四节课
    - 晚上 第一节课
    - 晚上 第二节课
    - 晚上 第三节课
    - 晚上 第四节课
