type Query {
    version: String,
    timestamp: Long,
    teacher(id: Short, name: String): TeacherInfo,
    student(id: String, name: String): StudentInfo,
    teachers: [Teacher],
    students: [Student]
}

type Teacher {
    teachID: Short!,
    teachName: String,
    sex: Boolean
}

type Student {
    stuName: String,
    stuID: String,
    classID: Short,
    siteNo: Byte,
    sex: Boolean,
    MAC: String,
}

type Students {
    name: String,
    students: [Student]
}

type Teachers {
    name: String,
    teachers: [Teacher]
}

union StudentInfo = Student | Students
union TeacherInfo = Teacher | Teachers
