# curl -X POST
#localhost:8443/student/sign-in-all
#-H "Content-Type: application/json"
#-d '{"AppID":3,"devices":[{"BName":"201730126030","Bdistance":"1.41","BMac":"E3:15:EA:C3:C4:C2"}],"md5":"EABB4A007A4EE7C7A63FD77E231CF4FB","type":"batch"}'
POST localhost:8443/student/sign-in-all
Content-Type: application/json

{"AppID":3,"devices":[{"BName":"201730126030","Bdistance":"1.41","BMac":"E3:15:EA:C3:C4:C2"}],"md5":"EABB4A007A4EE7C7A63FD77E231CF4FB","type":"batch"}


###



###

# curl -X POST
#localhost:8443/student/sign-in-all
#-H "Content-Type: application/json"
#-d '[{"MAC":"test","studId":"2001"},{"MAC":"devel","studId":"2002"}]'
#
POST localhost:8443/student/sign-in-all
Content-Type: application/json

[{"MAC":"1C-5A-4A-3C-6B-7A-B1","studId":"100000005"},{"MAC":"1C-5C-4A-3C-6B-7A-B1","studId":"100000005"}]

###

# 签到
# curl -X POST
#-v localhost:8443/student/sign-in
#-d MAC=1C-52-16-B5-5C-1C
#-d studId=100000001
POST localhost:8443/student/sign-in
Content-Type: application/x-www-form-urlencoded

MAC=1C-52-16-B5-5C-1C&studId=100000001

###

# curl -X GET localhost:8443/student/all
GET localhost:8443/student/all

###

# curl -X POST localhost:8443/auth -d username=devel -d password=devel
POST localhost:8443/auth
Content-Type: application/x-www-form-urlencoded

username=devel&password=devel

###

