debug: false

spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  mustache:
    check-template-location: false

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
    show-sql: false
    database-platform: org.hibernate.dialect.SQLServer2008Dialect


  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://39.104.110.210;database=dbPocketTest
    username: develop
    password: sql2020DB$$

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      fail_on_empty_beans: false

  quartz:
    auto-startup: true
    job-store-type: memory
    scheduler-name: task
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: todo-task
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true


server:
  port: 8443
  servlet:
    context-path: /

management:
  endpoint:
    logfile:
      external-file: logs/pocket.log
  endpoints:
    web:
      exposure:
        include: ["*","logfile"]

logging:
  level:
    org:
      springframework.boot.autoconfigure: ERROR
      quartz: ERROR
  config: classpath:log/log4j2.yml
